#include "gfx/Drawable.hpp"

#include "phong_shader_info.hpp" // generated by CSP

namespace bolt {
namespace gfx {

Drawable3d::Drawable3d() : SceneNode(SceneNode::NODE_TYPE_DRAWABLE) {
}

void Drawable3d::onDraw() {
    mProgram->setMat4(CSP_UNIFORM_PHONG_PC_MODEL, worldMtx());
}

} // gfx
} // bolt
