#include "gfx/FlatDrawable.hpp"

#include "gfx/common.h"

#include "flat_shader_info.hpp" // generated by CSP

#define ARRAY_SIZE(arr) (sizeof(arr) / sizeof(arr[0]))

namespace bolt {
namespace gfx {

// Vertex attribute layout:
// Attribute 0: position (3 floats) -> offset 0
static const VertexAttribute FLAT_VTX_ATTR[] = {
    {0, offsetof(FlatDrawableVertex, pos), 3, BOLT_F32, sizeof(FlatDrawableVertex)}, // position
};

const VertexAttribute* FlatDrawable::attributes() const {
    return FLAT_VTX_ATTR;
}

int FlatDrawable::attributeCount() const {
    return ARRAY_SIZE(FLAT_VTX_ATTR);
}

const csp::ProgramDescriptor& FlatDrawable::programDescriptor() const {
    return flat_descriptor;
}

void FlatDrawable::onDraw() {
    this->Drawable3d::onDraw();

    setPushConstant(CSP_UNIFORM_FLAT_PC_COLOR, &mColor);
}

} // gfx
} // bolt
