#include "gfx/PhongDrawable.hpp"

#include "gfx/common.h"

#include "phong_shader_info.hpp" // generated by CSP

#define ARRAY_SIZE(arr) (sizeof(arr) / sizeof(arr[0]))

using namespace bolt::math;

namespace bolt {
namespace gfx {

// Vertex attribute layout:
// Attribute 0: position (3 floats) -> offset 0
// Attribute 1: normal (3 floats) -> offset 12
static const VertexAttribute PHONG_VTX_ATTR[] = {
    {0, offsetof(PhongDrawableVertex, pos), 3, BOLT_F32, sizeof(PhongDrawableVertex)}, // position
    {1, offsetof(PhongDrawableVertex, nrm), 3, BOLT_F32, sizeof(PhongDrawableVertex)}  // normal
};

PhongDrawable::PhongDrawable() : mAmbient(Vector3f::ZERO), mDiffuse(Vector3f::ZERO), mSpecular(Vector3f::ZERO), mShininess(0.0f) {

}

const VertexAttribute* PhongDrawable::attributes() const {
    return PHONG_VTX_ATTR;
}

int PhongDrawable::attributeCount() const {
    return ARRAY_SIZE(PHONG_VTX_ATTR);
}

const csp::ProgramDescriptor& PhongDrawable::programDescriptor() const {
    return phong_descriptor;
}

void PhongDrawable::onDraw() {
    this->Drawable3d::onDraw();

    // can probably set all at once after being careful with alignment
    // also maybe not need mAmbient etc and use push constant storage directly
    setPushConstant(CSP_UNIFORM_PHONG_PC_AMBIENT, &mAmbient);
    setPushConstant(CSP_UNIFORM_PHONG_PC_DIFFUSE, &mDiffuse);
    setPushConstant(CSP_UNIFORM_PHONG_PC_SPECULAR, &mSpecular);
    setPushConstant(CSP_UNIFORM_PHONG_PC_SHININESS, &mShininess);
}

void PhongDrawable::setMaterial(const PhongMaterial& material) {
    setAmbient(material.ambient);
    setDiffuse(material.diffuse);
    setSpecular(material.specular);
    setShininess(material.shininess);
}

} // gfx
} // bolt
