#include "gfx/SkinnedPhongMesh.hpp"
#include "gfx/common.h"

#include "skinnedphong_shader_info.hpp" // generated by CSP

#define ARRAY_SIZE(arr) (sizeof(arr) / sizeof(arr[0]))

using namespace bolt::math;

namespace bolt {
namespace gfx {

static void writeMtxTransposed(const math::Matrix44f& m, float* dst) {
    for (int i = 0; i < 4; ++i) {
        for (int j = 0; j < 4; ++j) {
            dst[i * 4 + j] = m(j, i);
        }
    }
}

SkinnedPhongMesh::SkinnedPhongMesh(std::vector<SkinnedPhongMeshVertex> vertices,
                           std::vector<unsigned int> indices,
                           std::unordered_map<std::string, int32_t> boneMapping) :
                           mVertices(vertices), mIndices(indices), mBoneMapping(boneMapping),
                           mAmbient(Vector3f::ZERO), mDiffuse(Vector3f::ZERO), mSpecular(Vector3f::ZERO), mShininess(0.0f) {
}

static const VertexAttribute SKINNED_PHONG_VTX_ATTR[] = {
    {0, offsetof(SkinnedPhongMeshVertex, position), 3, BOLT_F32, sizeof(SkinnedPhongMeshVertex)},
    {1, offsetof(SkinnedPhongMeshVertex, normal), 3, BOLT_F32, sizeof(SkinnedPhongMeshVertex)},
    {2, offsetof(SkinnedPhongMeshVertex, boneIds), MAX_VTX_WEIGHTS, BOLT_I32, sizeof(SkinnedPhongMeshVertex)},
    {3, offsetof(SkinnedPhongMeshVertex, weights), MAX_VTX_WEIGHTS, BOLT_F32, sizeof(SkinnedPhongMeshVertex)},
};

const VertexAttribute* SkinnedPhongMesh::attributes() const {
    return SKINNED_PHONG_VTX_ATTR;
}

int SkinnedPhongMesh::attributeCount() const {
    return ARRAY_SIZE(SKINNED_PHONG_VTX_ATTR);
}

const csp::ProgramDescriptor& SkinnedPhongMesh::programDescriptor() const {
    return skinnedphong_descriptor;
}

void SkinnedPhongMesh::onDraw() {
    this->Drawable3d::onDraw();

    setPushConstant(CSP_UNIFORM_SKINNEDPHONG_PC_AMBIENT, &mAmbient);
    setPushConstant(CSP_UNIFORM_SKINNEDPHONG_PC_DIFFUSE, &mDiffuse);
    setPushConstant(CSP_UNIFORM_SKINNEDPHONG_PC_SPECULAR, &mSpecular);
    setPushConstant(CSP_UNIFORM_SKINNEDPHONG_PC_SHININESS, &mShininess);
}

void SkinnedPhongMesh::setBoneTransform(const std::string& name, math::Matrix44f tf) {
    auto it = mBoneMapping.find(name);
    if (it == mBoneMapping.end()) {
        return;
    }

    int32_t boneId = it->second;
    float colMajor[16];
    writeMtxTransposed(tf, colMajor);

    setUniform(CSP_UNIFORM_SKINNEDPHONG_BONES, colMajor, sizeof(colMajor), boneId * sizeof(colMajor));
}

void SkinnedPhongMesh::setPoseDefault() {
    math::Matrix44f identity;
    identity.setIdentity();

    for (auto& [name, boneId] : mBoneMapping) {
        setBoneTransform(name, identity);
    }
}

} // gfx
} // bolt
