#include "gfx/SkinnedMesh.hpp"
#include "gfx/common.h"

#include "skinned_shader_info.hpp" // generated by CSP
#include <SDL3/SDL_events.h>

#define ARRAY_SIZE(arr) (sizeof(arr) / sizeof(arr[0]))

namespace bolt {
namespace gfx {

static void writeMtxTransposed(const math::Matrix44f& m, float* dst) {
    for (int i = 0; i < 4; ++i) {
        for (int j = 0; j < 4; ++j) {
            dst[i * 4 + j] = m(j, i);
        }
    }
}

SkinnedMesh::SkinnedMesh(std::vector<SkinnedMeshVertex> vertices,
                           std::vector<unsigned int> indices,
                           std::vector<TextureDescriptor> textures,
                           std::unordered_map<std::string, int32_t> boneMapping) :
                           mVertices(vertices), mIndices(indices), mTextureDesc(textures),
                           mBoneMapping(boneMapping) {
}

// Vertex attribute layout:
// Attribute 0: position (3 floats) -> offset 0
// Attribute 1: normal (3 floats) -> offset 12
// Attribute 2: tex coords (2 floats) -> offset 20
static const VertexAttribute SKINNED_VTX_ATTR[] = {
    {0, offsetof(SkinnedMeshVertex, position), 3, BOLT_F32, sizeof(SkinnedMeshVertex)},
    {1, offsetof(SkinnedMeshVertex, normal), 3, BOLT_F32, sizeof(SkinnedMeshVertex)},
    {2, offsetof(SkinnedMeshVertex, texCoo), 2, BOLT_F32, sizeof(SkinnedMeshVertex)},
    {3, offsetof(SkinnedMeshVertex, tangent), 3, BOLT_F32, sizeof(SkinnedMeshVertex)},
    {4, offsetof(SkinnedMeshVertex, bitangent), 3, BOLT_F32, sizeof(SkinnedMeshVertex)},
    {5, offsetof(SkinnedMeshVertex, boneIds), MAX_VTX_WEIGHTS, BOLT_I32, sizeof(SkinnedMeshVertex)},
    {6, offsetof(SkinnedMeshVertex, weights), MAX_VTX_WEIGHTS, BOLT_F32, sizeof(SkinnedMeshVertex)},
};

const VertexAttribute* SkinnedMesh::attributes() const {
    return SKINNED_VTX_ATTR;
}

int SkinnedMesh::attributeCount() const {
    return ARRAY_SIZE(SKINNED_VTX_ATTR);
}

const csp::ProgramDescriptor& SkinnedMesh::programDescriptor() const {
    return skinned_descriptor;
}

void SkinnedMesh::setBoneTransform(const std::string& name, math::Matrix44f tf) {
    auto it = mBoneMapping.find(name);
    if (it == mBoneMapping.end()) {
        return;
    }

    int32_t boneId = it->second;
    float colMajor[16];
    writeMtxTransposed(tf, colMajor);

    setUniform(CSP_UNIFORM_SKINNED_BONES, colMajor, sizeof(colMajor), boneId * sizeof(colMajor));
}

void SkinnedMesh::setPoseDefault() {
    math::Matrix44f identity;
    identity.setIdentity();

    for (auto& [name, boneId] : mBoneMapping) {
        setBoneTransform(name, identity);
    }
}

} // gfx
} // bolt
