#include "gfx/TexturedMesh.hpp"
#include "gfx/common.h"

#include "textured_shader_info.hpp" // generated by CSP

#define ARRAY_SIZE(arr) (sizeof(arr) / sizeof(arr[0]))

namespace bolt {
namespace gfx {

TexturedMesh::TexturedMesh(std::vector<TexturedMeshVertex> vertices,
                           std::vector<unsigned int> indices,
                           std::vector<TextureDescriptor> textures) :
                           mVertices(vertices), mIndices(indices), mTextureDesc(textures) {
}

// Vertex attribute layout:
// Attribute 0: position (3 floats) -> offset 0
// Attribute 1: normal (3 floats) -> offset 12
// Attribute 2: tex coords (2 floats) -> offset 20
static const VertexAttribute MESH_VTX_ATTR[] = {
    {0, offsetof(TexturedMeshVertex, position), 3, BOLT_F32, sizeof(TexturedMeshVertex)}, // position
    {1, offsetof(TexturedMeshVertex, normal), 3, BOLT_F32, sizeof(TexturedMeshVertex)},   // normal
    {2, offsetof(TexturedMeshVertex, texCoo), 2, BOLT_F32, sizeof(TexturedMeshVertex)}    // texture coordinates
};

const VertexAttribute* TexturedMesh::attributes() const {
    return MESH_VTX_ATTR;
}

int TexturedMesh::attributeCount() const {
    return ARRAY_SIZE(MESH_VTX_ATTR);
}

const csp::ProgramDescriptor& TexturedMesh::programDescriptor() const {
    return textured_descriptor;
}

} // gfx
} // bolt
